source ~/.config/nvim/plugins/vim-plug.vim
source ~/.config/nvim/plugins/airline/airline.vim
source ~/.config/nvim/plugins/coc/coc.vim
source ~/.config/nvim/plugins/devicons/devicons.vim
source ~/.config/nvim/plugins/indentline/indentline.vim
source ~/.config/nvim/plugins/javascript/js.vim
source ~/.config/nvim/plugins/javascript/jsdoc.vim
source ~/.config/nvim/plugins/nerdtree/nerdtree.vim
source ~/.config/nvim/plugins/signify/signify.vim
